<a href="https://colab.research.google.com/github/AUMANSH/Data-Science-Projects/blob/main/AUMANSH_GUPTA_LIST_FUNCTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Lambda functions in Python are small, anonymous functions defined using the `lambda` keyword.
# They can take any number of arguments but can only have one expression.
# They are often used for short, simple operations where defining a full function would be unnecessary.

# Example:
double = lambda x: x * 2
print(double(5))  # Output: 10

10


In [ ]:
# Parameters vs Arguments:

# Parameters are the names listed in the function definition. They act as placeholders for the values that will be passed to the function when it's called.
# Arguments are the actual values passed to the function when it's called. They correspond to the parameters in the function definition.

# Purpose of a Return Statement:

# A return statement is used to send a value back from a function to the place where it was called. It allows the function to produce a result that can be used in other parts of the program.




# Default Arguments:

# Default arguments are values assigned to parameters in the function definition. If a value for that parameter is not provided when the function is called, the default value is used.

def greet(name, greeting="Hello"):
  """
  This function greets a person with a given name and greeting.

  Args:
    name: The name of the person to greet.
    greeting: The greeting to use (default is "Hello").
  """
  print(f"{greeting}, {name}!")

greet("Bob")           # Output: Hello, Bob!
greet("Eve", "Hi")     # Output: Hi, Eve!


Hello, Bob!
Hi, Eve!


In [ ]:
# Returning Multiple Values:

# You can return multiple values from a function by packing them into a tuple or a list and then unpacking them when the function is called.

def get_name_and_age():
  """
  This function returns a tuple containing a name and an age.
  """
  name = "Alice"
  age = 30
  return name, age

# Unpacking the returned values:
person_name, person_age = get_name_and_age()
print(person_name)  # Output: Alice
print(person_age)   # Output: 30



Alice
30


In [ ]:
# Function to Calculate Sum:

def sum_numbers(a, b):
  """
  This function takes two numbers as input and returns their sum.

  Args:
    a: The first number.
    b: The second number.

  Returns:
    The sum of a and b.
  """
  return a + b

In [ ]:
# Variable Scope and Functions

# In Python, variable scope refers to the region of the code where a variable is accessible.
# Variables defined inside a function have local scope, meaning they can only be accessed within that function.
# Variables defined outside of any function have global scope and can be accessed from anywhere in the code.

# Example
def my_function():
  x = 10  # Local variable
  print(x)

my_function()  # Output: 10
# print(x)  # This would raise an error because x is not defined in the global scope




10


In [ ]:
# Factorial Function Using Recursion

def factorial(n):
  """
  This function calculates the factorial of a number using recursion.
  """
  if n == 0:
    return 1
  else:
    return n * factorial(n - 1)

result = factorial(5)
print(result)  # Output: 120

120


In [ ]:
import numpy as np

# Create a 2x3 NumPy array filled with zeros
zeros_array = np.zeros((2, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

my_list = [1, 2, 3, 4]
numpy_array = np.array(my_list)

print(numpy_array)  # Output: [1 2 3 4]


[1 2 3 4]


In [ ]:
import numpy as np

# Create two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Perform element-wise addition
result = arr1 + arr2

print(result)  # Output: [5 7 9]

[5 7 9]


In [ ]:
# Python lists can store elements of different data types, while NumPy arrays are designed to store elements of the same data type.
# This allows for efficient numerical operations and optimized memory usage in NumPy arrays.

# Example:
my_list = [1, "hello", 3.14]  # A list with different data types
my_array = np.array([1, 2, 3, 4])  # A NumPy array with integers

print(my_list)
print(my_array)


[1, 'hello', 3.14]
[1 2 3 4]


In [ ]:
# NumPy arrays support vectorized operations, meaning you can perform operations on entire arrays without explicit loops.
# This leads to significant performance gains compared to iterating over lists.

# Example:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Element-wise addition of arrays
print(c)  # Output: [5 7 9]



[5 7 9]


In [ ]:
# NumPy provides a wide range of functions for mathematical and scientific computations that are not available for lists.
# These functions are optimized for array operations and can handle large datasets efficiently.

# Example:
mean = np.mean(my_array)
std_dev = np.std(my_array)
print(mean)  # Output: 2.5
print(std_dev)  # Output: 1.118033988749895


2.5
1.118033988749895


In [ ]:
import numpy as np

In [ ]:
# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Calculate mean and standard deviation
mean = np.mean(my_array)
std_dev = np.std(my_array)

print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: 3.0
Standard Deviation: 1.4142135623730951


In [ ]:
# Common functions for creating NumPy arrays:

# Zeros: Creates an array filled with zeros.
zeros_array = np.zeros(5)  # Creates an array of 5 zeros
print(zeros_array)  # Output: [0. 0. 0. 0. 0.]

# Ones: Creates an array filled with ones.
ones_array = np.ones((2, 3))  # Creates a 2x3 array of ones
print(ones_array)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]]

# Full: Creates an array filled with a specified value.
full_array = np.full((3, 2), 7)  # Creates a 3x2 array filled with 7s
print(full_array)
# Output:
# [[7 7]
#  [7 7]
#  [7 7]]

# Arange: Creates an array with evenly spaced values within a given interval.
arange_array = np.arange(10, 20, 2)  # Creates an array from 10 to 19 (exclusive) with a step of 2
print(arange_array)  # Output: [10 12 14 16 18]

# Linspace: Creates an array with evenly spaced values between a start and end point.
linspace_array = np.linspace(0, 1, 5)  # Creates an array of 5 evenly spaced values from 0 to 1 (inclusive)
print(linspace_array)  # Output: [0.   0.25 0.5  0.75 1.  ]


[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]
 [7 7]]
[10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Accessing elements in NumPy arrays:

# 1D array:
arr1d = np.array([1, 2, 3, 4])
print(arr1d[0])   # Access the first element (index 0): Output: 1
print(arr1d[-1])  # Access the last element (index -1): Output: 4
print(arr1d[1:3]) # Access a slice from index 1 to 2 (exclusive): Output: [2 3]

# 2D array:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[0, 1])  # Access the element at row 0, column 1: Output: 2
print(arr2d[:, 1])  # Access all elements in column 1: Output: [2 5]
print(arr2d[1, :])  # Access all elements in row 1: Output: [4 5 6]


1
4
[2 3]
2
[2 5]
[4 5 6]


In [ ]:
# Broadcasting in NumPy:

# Broadcasting allows arithmetic operations between arrays of different shapes under certain conditions.
# NumPy automatically expands the smaller array to match the shape of the larger array.

a = np.array([1, 2, 3])
b = 2
result = a * b  # Broadcasting: b is multiplied with each element of a
print(result)  # Output: [2 4 6]


[2 4 6]


In [ ]:
# Matrix multiplication using NumPy:

# The `np.dot()` function is used for matrix multiplication.

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)
# Output:
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]
