<a href="https://colab.research.google.com/github/AUMANSH/Data-Science-Projects/blob/main/LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
i=[1,2,3,4]
np.array(i)

array([1, 2, 3, 4])

In [20]:
c=np.array([2,3,4,1])
c.shape

(4,)

In [17]:
b=np.array([[1,2],[3,4]])
b.shape

(2, 2)

In [13]:
a=np.array([[[1,2],[3,4],[5,6]]])

In [15]:
a.shape

(1, 3, 2)

In [19]:
a.ndim

3

In [34]:
np.zeros(3)

array([0., 0., 0.])

In [38]:
x=np.array([1,2,4,5,6,9,8,7,3])
a=np.arange(0,9)
a
x

array([1, 2, 4, 5, 6, 9, 8, 7, 3])

In [40]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [41]:
np.zeros([2,2],dtype=str)

array([['', ''],
       ['', '']], dtype='<U1')

In [42]:
np.ones(3)

array([1., 1., 1.])

In [43]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [48]:
 f = np.eye(2)
 f

array([[1., 0.],
       [0., 1.]])

In [49]:
 np.random.random((2,2))

array([[0.4404285 , 0.17912151],
       [0.99812472, 0.74891881]])

In [51]:
np.empty((3,2))

array([[4.90998611e-310, 0.00000000e+000],
       [6.72712907e-310, 4.78179664e+180],
       [7.20366915e+159, 2.28896110e+243]])

In [52]:
np.random.randint(0,10,2)

array([3, 0])

In [54]:
np.random.rand(2)

array([0.53324276, 0.70444406])

In [55]:
np.eye(1,dtype=int)

array([[1]])

In [56]:
np.empty((3,2))

array([[4.90998611e-310, 0.00000000e+000],
       [6.72712907e-310, 4.78179664e+180],
       [7.20366915e+159, 2.28896110e+243]])

In [59]:
 np.save('my_array', a)


In [60]:
np.savez('array.npz', a, b)

In [61]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
 a.sum()

36

In [64]:
a.min()

0

In [65]:
b.max(axis=0)

array([3, 4])

In [66]:
b.cumsum(axis=1)

array([[1, 3],
       [3, 7]])

In [67]:
a.mean()

4.0

In [76]:
arr = np.arange(0,25)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])